# Generated by Django 4.2.18 on 2025-02-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_values', models.JSONField()),
                ('y_values', models.JSONField()),
            ],
        ),
    ]
